#!/usr/bin/env python3
"""Embed conformance vectors as a Rust constant (vectors.rs) for crate-free rustc check."""
import json, pathlib
ROOT = pathlib.Path(__file__).parent
vecs = json.loads((ROOT / "out/conformance.json").read_text())["vectors"]
lines = ["// GENERATED by embed_vectors.py — canonical vectors from out/conformance.json",
         "type V = (u8, u8, u8, u8, u8, u32); // (glyph, route, weight, flags, buzz, word)",
         f"const VECTORS: [V; {len(vecs)}] = ["]
for v in vecs:
    lines.append(f"    ({v['glyph']}, {v['route']}, {v['weight']}, {v['flags']}, {v['buzz']}, {v['word']}),")
lines.append("];")
(ROOT / "vectors.rs").write_text("\n".join(lines) + "\n")
print(f"[embed] {len(vecs)} vectors -> vectors.rs")
